export { HeroSection } from './HeroSection'
export { PlatformHighlights } from './PlatformHighlights'
export { FeaturedCourses } from './FeaturedCourses'
export { CourseCard } from './CourseCard'
export { WhyEduFlow } from './WhyEduFlow'
export { HowItWorks } from './HowItWorks'
export { LearningExperience } from './LearningExperience'
export { PlatformCapabilities } from './PlatformCapabilities'
export { FAQSection } from './FAQSection'
export { FinalCTA } from './FinalCTA'

